language: python
python:
  - "3.3"
  - "3.4"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# install: PLEASE CHANGE ME
install:
    pip install coveralls --use-mirrors

# command to run tests, e.g. python setup.py test
script:
    coverage run --source=okfncart setup.py test

after_success:
    coveralls

notifications:
  email:
    - christian.ledermann@gmail.com
